name: trainers

services:
  frontend:
    restart: always
    build:
      context: frontend
    ports:
      - 5000:5000
  backend:
    restart: always
    build:
      context: backend
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ChangeMe


  database:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - trainers-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  trainers-data: