name: trainers

services:
  frontend:
    restart: always
    build:
      context: frontend
  backend:
    restart: always
    build:
      context: backend
    depends_on:
      - database
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ChangeMe
      - SPRING_CORS_ORIGIN=http://localhost:80


  database:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - trainers-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  proxy:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  trainers-data:
